-- REMEMBER TO ADD DROP TABLE IF EXISTS STATEMENTS HERE, ORDER MATTERS
DROP TABLE IF EXISTS departments;
DROP TABLE IF EXISTS roles;
DROP TABLE IF EXISTS employees;

CREATE TABLE departments (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(30) NOT NULL
);

CREATE TABLE roles (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(30) NOT NULL,
salary DECIMAL NOT NULL, -- RESEARCH MORE FOR (P,D)
department_id INTEGER,
CONSTRAINT fk_department FOREIGN KEY (department_id) REFERENCES departments(id) ON DELETE SET NULL
);

CREATE TABLE employees (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
first_name VARCHAR(30) NOT NULL,
last_name VARCHAR(30) NOT NULL,
role_id INTEGER,
manager_id INTEGER,
CONSTRAINT fk_role FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE SET NULL
);

-- PICK UP WORKING ON CONSTRAINTS THEY ARE NOT FINISHED/NEED TWEAKS IN THE TABLE STATEMENTS
-- CHECK IF ORDER OF TABLE DROPPING MATTERS
-- ASK ABOUT manager_id AND HOW IT WORKS, ALSO IF IT WORKS AS IS
